import { ICommunity, ISermon } from '@/app/variables/interfaces';

const sermonsType1: ISermon[] = [
  {
    id: 296,
    name: '준비된 삶',
    desc: '얻어맞고 정신 번쩍 들지말고 말씀으로 정신 번쩍 들자!',
    url: null,
    type: 1,
    viewCount: 2,
    createdAt: '2024-12-30 23:39:11',
    nameEn: 'Prepared life',
    descEn: "Don't lose your senses after getting hit. Let’s wake up with the Word!",
  },
  {
    id: 288,
    name: '하나님께서 우리에게 원하시는 것',
    desc: '하나님을 사랑 \n이웃을 사랑 \n하나님나라와 의를 이루는데 수고하며 헌신하는 것 \n주님을 생각하며 말씀을 따름',
    url: null,
    type: 1,
    viewCount: 2,
    createdAt: '2024-09-10 00:00:00',
    nameEn: 'What God Wants from Us',
    descEn:
      'love god \nlove your neighbors \nToil and dedicate yourself to achieving the kingdom of God and righteousness \nThinking of the Lord and following His Word',
  },
  {
    id: 289,
    name: '마귀의 계략이 작동할 수 있는 사람의 인성',
    desc: '이기주의, 게으름, 자기합리화, 타협주의, 변명과 구실',
    url: null,
    type: 1,
    viewCount: 1,
    createdAt: '2024-09-10 00:00:00',
    nameEn: 'The humanity of Sram that allows the devil’s schemes to work',
    descEn: 'Egoism, laziness, self-justification, compromise, excuses and excuses',
  },
  {
    id: 290,
    name: '말씀과 기도로 무기 삼고 믿음으로 나아가야 하는 교회',
    desc: '말씀의 실천(나의 몫)으로 나가야하는 교회 \n우리 교회의 머리는 예수 그리스도',
    url: null,
    type: 1,
    viewCount: 0,
    createdAt: '2024-09-10 00:00:00',
    nameEn: 'A church that must advance in faith, armed with the word and prayer.',
    descEn:
      'A church that must move forward by putting the word into practice (my share) \nThe head of our church is Jesus Christ',
  },
];

const sermonsType0: ISermon[] = [
  {
    id: 297,
    name: '눈물로 씨를 뿌리는 자가 되자(4)',
    desc: '시편 126편',
    url: 'YJ5Pz5gO-zI',
    type: 0,
    viewCount: 0,
    createdAt: '2025-01-07 00:00:00',
    nameEn: 'Let’s become those who sow seeds with tears.',
    descEn: 'Psalms126',
  },
  {
    id: 295,
    name: '눈물로 씨를 뿌리는 자가 되자(3)',
    desc: '시편 126편',
    url: '4edL424GKfg',
    type: 0,
    viewCount: 0,
    createdAt: '2024-12-19 00:00:00',
    nameEn: 'Let’s become those who sow seeds with tears.',
    descEn: 'Psalms126',
  },
  {
    id: 294,
    name: '눈물로 씨를 뿌리는 자가 되자(2)',
    desc: '시편 126편',
    url: 'VeiLYiYarpI',
    type: 0,
    viewCount: 0,
    createdAt: '2024-11-28 00:00:00',
    nameEn: 'Let’s become those who sow seeds with tears.',
    descEn: 'Psalms126',
  },
];

const communities: ICommunity[] = [
  {
    id: 43,
    name: '나의 인생을 돌아보기',
    desc: '오예민 자매',
    type: 2,
    url: '',
    viewCount: 0,
    createdAt: '2024-11-08 00:00:00',
    nameEn: 'Looking back on my life',
    descEn: 'Sister Oh ye-min',
    files: [
      {
        id: 76,
        communityId: 43,
        url: '2024/11/8/',
        caption: '3',
        downloadCount: null,
        createdAt: '2024-11-08 19:33',
        captionEn: null,
      },
    ],
  },
  {
    id: 42,
    name: '나의 인생을 돌아보기',
    desc: '오민혁 형제',
    type: 2,
    url: '',
    viewCount: 0,
    createdAt: '2024-11-07 00:00:00',
    nameEn: 'Looking back on my life',
    descEn: 'Brother Oh min-hyuk',
    files: [
      {
        id: 77,
        communityId: 42,
        url: '2024/11/7/',
        caption: '2',
        downloadCount: null,
        createdAt: '2024-11-07 19:33',
        captionEn: null,
      },
    ],
  },
  {
    id: 41,
    name: '센뚜미르목사님 후원',
    desc: '센뚜미르목사님 후원',
    type: 0,
    url: '',
    viewCount: 0,
    createdAt: '2024-10-20 00:00:00',
    nameEn: 'Pastor Santu Mir visit',
    descEn: 'Pastor Santu Mir visit',
    files: [
      {
        id: 74,
        communityId: 41,
        url: '2024/10/20/',
        caption: '3',
        downloadCount: null,
        createdAt: '2024-10-20 00:00:00',
        captionEn: null,
      },
    ],
  },
  {
    id: 40,
    name: '김철목사님 방문',
    desc: '김철목사님 방문',
    type: 1,
    url: '',
    viewCount: 0,
    createdAt: '2024-10-09 00:00:00',
    nameEn: 'Pastor Kim Cheol’s visit',
    descEn: 'Pastor Kim Cheol’s visit',
    files: [
      {
        id: 73,
        communityId: 40,
        url: '2024/10/9/',
        caption: '2',
        downloadCount: null,
        createdAt: '2024-10-10 00:25:50.000000 +00:00',
        captionEn: null,
      },
    ],
  },
  {
    id: 44,
    name: '교회 후원사역 후기',
    desc: '한채리 자매',
    type: 2,
    url: '',
    viewCount: 0,
    createdAt: '2024-09-28 00:00:00',
    nameEn: 'Review of church sponsorship ministry',
    descEn: 'Sister Han Chae-ri',
    files: [
      {
        id: 75,
        communityId: 44,
        url: '2024/9/28/',
        caption: '1',
        downloadCount: null,
        createdAt: '2024-09-28 19:33:04',
        captionEn: null,
      },
    ],
  },
];

export { sermonsType0, sermonsType1, communities };
